{
 "title": "Prometheus - metrics de nginx en challenger-004 namespace",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Estados del ultimo scrape",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_up{namespace=\"challenger-004\", pod=\"nginx-6bff48bf56-qts96\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIstorico de conexiones activas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_active{namespace=\"challenger-004\", pod=\"nginx-6bff48bf56-qts96\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIstorico de conexiones procesadas ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_handled{namespace=\"challenger-004\", pod=\"nginx-6bff48bf56-qts96\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIstorico de peticiones HTTP totales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{namespace=\"challenger-004\", pod=\"nginx-6bff48bf56-qts96\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje uso  CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"challenger-004\", pod=\"nginx-6bff48bf56-qts96\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}